version: '3.8'



services:
  postgres:
    restart: "always"
    container_name: "url-short"
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: urls
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - ./pg:/var/lib/postgresql/data/pgdata